version: '3.8'

services:
  nafullstacku:
    image: nginx:1.25.2
    volumes:
      - "./nafullstacku/src:/usr/share/nginx/html"

  marcin:
    image: nginx:1.25.2
    volumes:
      - "./marcin/src:/usr/share/nginx/html"

  reverse_proxy:
    image: nginx:1.25.2
    volumes:
      - './reverse-proxy/app.conf:/etc/nginx/conf.d/app.conf'
    ports:
      - "80:80"
